### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by lif314** [hetolin/PourIt#1]
Thank you for your intriguing work! I'm eager to learn when you plan to release the code.

**Comment by hetolin** [comment]
Hello, thank you for your interest in our work.  Currently, I have the original, untidy code on my computer. We plan to release the cleaned-up code within the next two weeks.

**Comment by lif314** [comment]
> Hello, thank you for your interest in our work. Currently, I have the original, untidy code on my computer. We plan to release the cleaned-up code within the next two weeks.

Thanks! Looking forward to it!

**Comment by hetolin** [comment]
@lif314 Hi, we have released our code and pre-trained weights.
